### PR TITLE
Rollup

### PR DESCRIPTION
**Pull request by dpca**
Changes curious-js to use rollup for module bundling into ES6 modules, with backwards compatibility using UMD and CommonJS. This also opens up a path for using babel in the future.

### CODE REVIEW

**Comment by myw** [comment]
LGTM; please provide a description and verify that documentation still looks as expected when built. Other than that, it's good to go.

**Review by myw — APPROVED** [review]
Overall, LGTM:

Please add a description and verify that the generated documentation looks as expected (scope can do weird things to JSDoc sometimes).

Also, this is a breaking change to bower usage of the repo, because bower won't pull in or reference anything that isn't checked in, nor will bower run any scripts pre or post checkout. No production code should be using bower.json to pull in curious.js anymore, so I think we make this change a major version bump, notify users, and go bravely forward into the night.

**Comment by dpca** [comment]
Description added and documentation looks good locally. I also just removed the remaining bower parts if you want to take a glance at the latest commit. I thought unpkg still supported bower which is why I left it in, but it turns out they removed support a while ago too.

My plan for release is the following:
1) Tag as version `3.0.0` once merged
2) Run `scripts/release_doc`
3) Alert users in slack of the breaking change w/ removal of bower support

I also see that we use GitHub releases, should I create a release for this? Is that done manually?

**Comment by myw** [comment]
@dpca thanks! this looks good and is ready for merge. Before you merge, please do the following: Merge `v2` into master, and change the default branch of the repo back to `master` from `v2`. Then, update the documentation in this MR to no longer refer to `v2` as the master branch. Then merge your MR into `master`, tag the merged-in master with `v3.0.0` (you should be able to use `npm version` for this), and push your tags up. Once you've created that tag, you can manually turn that tag into a release with GitHub, by adding a new Release from the tags, and writing a quick Markdown description of the new changes. NPM release should happen automatically when Travis runs on the 3.0.0 tagged version.

**Pull request merged**
